---
title: "Final Project Expectations and Regulations"
abstract: "Final Project"
format:
  revealjs:
    footer: "[back to the lecture slides on the course website](https://tmieno2.github.io/Data-Science-with-R-Quarto/lectures/)"
    theme: [default, custom.scss]
    fontsize: 1.2em
    callout-icon: false
    scrollable: true
    echo: true
    fig-dpi: 400
---

## Logistics

:::{.callout-note title="Submission"}
+ Both qmd and html
+ Use the submission link I will provide
:::

<br>

::: {.callout-note title="Deadline"}
+ Final project is due Dec 19th.
+ Final project approval is due Nov 5th.
:::

## Final Project Structure

::: {.panel-tabset}

### Introduction (2)

In a single paragraph, 

+ Describe what you are trying to find out (research question)
+ Describe why the research question is worthwhile answering

### Data Description and Processing (25)

+ Describe what the final dataset would look like
  * observational units (plots in an agronomic experiment, county, gene expression, etc)
  * temporal and spatial scales if applicable 
  * list of variables 
+ Provide summary statistics for each of the raw datasets using tables
+ Generate appropriate figures that help the readers understand the nature of the datasets 
+ Process raw datasets and combine them

### Exploratory Analysis (12)

+ Explore visually the relationship of variables you are interested in understanding 
+ Run statistical analysis (unless impossible) and explain the results (Note: if you are Ag Econ/Econ students, you must run at least one regression)
+ Present the results in a table and draw conclusions

### Conclusion (1)

+ Summarize the report in several sentences
:::
<!--end of panel-->

<br>

## Regulations and Bonus Points

:::{.callout-note title="Regulation"}
+ Use Quarto (.qmd) 
+ Use at least two raw datasets that need to be combined before analysis, and you need to merge the datasets at some point 
+ Describe the purpose for each of the R code chunks 
+ Use `tidyverse` functions wherever possible (for practice)
+ Use `ggplot2` for all the figures you generate 
+ Use one of `gt`, `flextable`, and `modelsummary` to create tables (Note: if you are in Ag Econ/Econ, you need to create at least one regression results table using `modelsummary`)
+ Your project must include spatial operations using at least one of `sf`, `raster`, and `stars` packages if you are in Agronomy and Horticulture.
:::

<br>

:::{.callout-note title="Bonus Points"}
+ Define and use a function(s) in a meaningful way (2 points)
+ Use looping in a meaningful way and parallelize it (2 points)
+ Use more than three types of figures in a meaningful way (2 points)
:::


## Hints

:::{.callout-note title="Hint 1"}
The fastest and easiest way to find your final project is to simply bring back one of your old projects (whether it was done in R or outside of R) and redo everything (data wrangling, visualization, statistical analysis, reporting) using R, taking advantage of what you have learned in the class.
:::

<br>

:::{.callout-note title="Hint 2"}
Assignment 1 is very similar to what your final project should look like.
:::

<br>

:::{.callout-note title="Hint 3"}
This assignment is like writing a journal article except you provide lots of details about how you process datasets with all the R codes displayed.
:::





 