---
title: "Course Calendar, Fall 2026"
---

Class meets **Monday and Wednesday**, August 24 -- December 12, 2026. Final exams December 14--18. **29 class meetings total.**

<p class="legend">
<span class="swatch class-day"></span> Class meets &nbsp;&nbsp;
<span class="swatch holiday"></span> University / student holiday, no class
</p>

<style>
.cal { border-collapse: collapse; width: 100%; max-width: 780px; margin: 1.5em 0; font-size: 0.9em; }
.cal caption { font-size: 1.3em; font-weight: 600; text-align: left; padding: 0.4em 0; }
.cal th { background: #f2f2f2; border: 1px solid #ddd; padding: 0.4em; font-weight: 600; }
.cal td { border: 1px solid #ddd; height: 70px; width: 14.28%; vertical-align: top; padding: 0.3em; }
.cal td.out { background: #fafafa; }
.cal .num { color: #666; font-size: 0.9em; }
.cal td.class-day { background: #dceaf7; }
.cal td.holiday { background: #f7e0dc; }
.cal .tag { display: block; margin-top: 0.2em; font-size: 0.8em; font-weight: 600; line-height: 1.2; }
.legend .swatch { display: inline-block; width: 1em; height: 1em; border: 1px solid #ddd; vertical-align: -0.15em; }
.legend .class-day { background: #dceaf7; }
.legend .holiday { background: #f7e0dc; }
</style>

<table class="cal">
<caption>August 2026</caption>
<thead><tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th></tr></thead><tbody>
<tr>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class=""><span class="num">1</span></td>
</tr>
<tr>
<td class=""><span class="num">2</span></td>
<td class=""><span class="num">3</span></td>
<td class=""><span class="num">4</span></td>
<td class=""><span class="num">5</span></td>
<td class=""><span class="num">6</span></td>
<td class=""><span class="num">7</span></td>
<td class=""><span class="num">8</span></td>
</tr>
<tr>
<td class=""><span class="num">9</span></td>
<td class=""><span class="num">10</span></td>
<td class=""><span class="num">11</span></td>
<td class=""><span class="num">12</span></td>
<td class=""><span class="num">13</span></td>
<td class=""><span class="num">14</span></td>
<td class=""><span class="num">15</span></td>
</tr>
<tr>
<td class=""><span class="num">16</span></td>
<td class=""><span class="num">17</span></td>
<td class=""><span class="num">18</span></td>
<td class=""><span class="num">19</span></td>
<td class=""><span class="num">20</span></td>
<td class=""><span class="num">21</span></td>
<td class=""><span class="num">22</span></td>
</tr>
<tr>
<td class=""><span class="num">23</span></td>
<td class="class-day"><span class="num">24</span><span class="tag">Class 1</span></td>
<td class=""><span class="num">25</span></td>
<td class="class-day"><span class="num">26</span><span class="tag">Class 2</span></td>
<td class=""><span class="num">27</span></td>
<td class=""><span class="num">28</span></td>
<td class=""><span class="num">29</span></td>
</tr>
<tr>
<td class=""><span class="num">30</span></td>
<td class="class-day"><span class="num">31</span><span class="tag">Class 3</span></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
</tr>
</tbody></table>
<table class="cal">
<caption>September 2026</caption>
<thead><tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th></tr></thead><tbody>
<tr>
<td class="out"></td>
<td class="out"></td>
<td class=""><span class="num">1</span></td>
<td class="class-day"><span class="num">2</span><span class="tag">Class 4</span></td>
<td class=""><span class="num">3</span></td>
<td class=""><span class="num">4</span></td>
<td class=""><span class="num">5</span></td>
</tr>
<tr>
<td class=""><span class="num">6</span></td>
<td class="holiday"><span class="num">7</span><span class="tag">No class<br>Labor Day</span></td>
<td class=""><span class="num">8</span></td>
<td class="class-day"><span class="num">9</span><span class="tag">Class 5</span></td>
<td class=""><span class="num">10</span></td>
<td class=""><span class="num">11</span></td>
<td class=""><span class="num">12</span></td>
</tr>
<tr>
<td class=""><span class="num">13</span></td>
<td class="class-day"><span class="num">14</span><span class="tag">Class 6</span></td>
<td class=""><span class="num">15</span></td>
<td class="class-day"><span class="num">16</span><span class="tag">Class 7</span></td>
<td class=""><span class="num">17</span></td>
<td class=""><span class="num">18</span></td>
<td class=""><span class="num">19</span></td>
</tr>
<tr>
<td class=""><span class="num">20</span></td>
<td class="class-day"><span class="num">21</span><span class="tag">Class 8</span></td>
<td class=""><span class="num">22</span></td>
<td class="class-day"><span class="num">23</span><span class="tag">Class 9</span></td>
<td class=""><span class="num">24</span></td>
<td class=""><span class="num">25</span></td>
<td class=""><span class="num">26</span></td>
</tr>
<tr>
<td class=""><span class="num">27</span></td>
<td class="class-day"><span class="num">28</span><span class="tag">Class 10</span></td>
<td class=""><span class="num">29</span></td>
<td class="class-day"><span class="num">30</span><span class="tag">Class 11</span></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
</tr>
</tbody></table>
<table class="cal">
<caption>October 2026</caption>
<thead><tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th></tr></thead><tbody>
<tr>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class=""><span class="num">1</span></td>
<td class=""><span class="num">2</span></td>
<td class=""><span class="num">3</span></td>
</tr>
<tr>
<td class=""><span class="num">4</span></td>
<td class="class-day"><span class="num">5</span><span class="tag">Class 12</span></td>
<td class=""><span class="num">6</span></td>
<td class="class-day"><span class="num">7</span><span class="tag">Class 13</span></td>
<td class=""><span class="num">8</span></td>
<td class=""><span class="num">9</span></td>
<td class=""><span class="num">10</span></td>
</tr>
<tr>
<td class=""><span class="num">11</span></td>
<td class="class-day"><span class="num">12</span><span class="tag">Class 14</span></td>
<td class=""><span class="num">13</span></td>
<td class="class-day"><span class="num">14</span><span class="tag">Class 15</span></td>
<td class=""><span class="num">15</span></td>
<td class=""><span class="num">16</span></td>
<td class=""><span class="num">17</span></td>
</tr>
<tr>
<td class=""><span class="num">18</span></td>
<td class="holiday"><span class="num">19</span><span class="tag">No class<br>Fall Break</span></td>
<td class=""><span class="num">20</span></td>
<td class="class-day"><span class="num">21</span><span class="tag">Class 16</span></td>
<td class=""><span class="num">22</span></td>
<td class=""><span class="num">23</span></td>
<td class=""><span class="num">24</span></td>
</tr>
<tr>
<td class=""><span class="num">25</span></td>
<td class="class-day"><span class="num">26</span><span class="tag">Class 17</span></td>
<td class=""><span class="num">27</span></td>
<td class="class-day"><span class="num">28</span><span class="tag">Class 18</span></td>
<td class=""><span class="num">29</span></td>
<td class=""><span class="num">30</span></td>
<td class=""><span class="num">31</span></td>
</tr>
</tbody></table>
<table class="cal">
<caption>November 2026</caption>
<thead><tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th></tr></thead><tbody>
<tr>
<td class=""><span class="num">1</span></td>
<td class="class-day"><span class="num">2</span><span class="tag">Class 19</span></td>
<td class=""><span class="num">3</span></td>
<td class="class-day"><span class="num">4</span><span class="tag">Class 20</span></td>
<td class=""><span class="num">5</span></td>
<td class=""><span class="num">6</span></td>
<td class=""><span class="num">7</span></td>
</tr>
<tr>
<td class=""><span class="num">8</span></td>
<td class="class-day"><span class="num">9</span><span class="tag">Class 21</span></td>
<td class=""><span class="num">10</span></td>
<td class="class-day"><span class="num">11</span><span class="tag">Class 22</span></td>
<td class=""><span class="num">12</span></td>
<td class=""><span class="num">13</span></td>
<td class=""><span class="num">14</span></td>
</tr>
<tr>
<td class=""><span class="num">15</span></td>
<td class="class-day"><span class="num">16</span><span class="tag">Class 23</span></td>
<td class=""><span class="num">17</span></td>
<td class="class-day"><span class="num">18</span><span class="tag">Class 24</span></td>
<td class=""><span class="num">19</span></td>
<td class=""><span class="num">20</span></td>
<td class=""><span class="num">21</span></td>
</tr>
<tr>
<td class=""><span class="num">22</span></td>
<td class="class-day"><span class="num">23</span><span class="tag">Class 25</span></td>
<td class=""><span class="num">24</span></td>
<td class="holiday"><span class="num">25</span><span class="tag">No class<br>Thanksgiving</span></td>
<td class=""><span class="num">26</span></td>
<td class=""><span class="num">27</span></td>
<td class=""><span class="num">28</span></td>
</tr>
<tr>
<td class=""><span class="num">29</span></td>
<td class="class-day"><span class="num">30</span><span class="tag">Class 26</span></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
<td class="out"></td>
</tr>
</tbody></table>
<table class="cal">
<caption>December 2026</caption>
<thead><tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th></tr></thead><tbody>
<tr>
<td class="out"></td>
<td class="out"></td>
<td class=""><span class="num">1</span></td>
<td class="class-day"><span class="num">2</span><span class="tag">Class 27</span></td>
<td class=""><span class="num">3</span></td>
<td class=""><span class="num">4</span></td>
<td class=""><span class="num">5</span></td>
</tr>
<tr>
<td class=""><span class="num">6</span></td>
<td class="class-day"><span class="num">7</span><span class="tag">Class 28</span></td>
<td class=""><span class="num">8</span></td>
<td class="class-day"><span class="num">9</span><span class="tag">Class 29</span></td>
<td class=""><span class="num">10</span></td>
<td class=""><span class="num">11</span></td>
<td class=""><span class="num">12</span></td>
</tr>
<tr>
<td class=""><span class="num">13</span></td>
<td class=""><span class="num">14</span></td>
<td class=""><span class="num">15</span></td>
<td class=""><span class="num">16</span></td>
<td class=""><span class="num">17</span></td>
<td class=""><span class="num">18</span></td>
<td class=""><span class="num">19</span></td>
</tr>
<tr>
<td class=""><span class="num">20</span></td>
<td class=""><span class="num">21</span></td>
<td class=""><span class="num">22</span></td>
<td class=""><span class="num">23</span></td>
<td class=""><span class="num">24</span></td>
<td class=""><span class="num">25</span></td>
<td class=""><span class="num">26</span></td>
</tr>
<tr>
<td class=""><span class="num">27</span></td>
<td class=""><span class="num">28</span></td>
<td class=""><span class="num">29</span></td>
<td class=""><span class="num">30</span></td>
<td class=""><span class="num">31</span></td>
<td class="out"></td>
<td class="out"></td>
</tr>
</tbody></table>

## No-class days

+ **Monday, September 7** --- Labor Day (university holiday)
+ **Monday, October 19** --- Fall Break (student holiday, Oct 19--20)
+ **Wednesday, November 25** --- Thanksgiving Break (student holiday, break runs Nov 25--29)
